from enum import StrEnum, unique


@unique
class SubscriptionStatus(StrEnum):
    CHECKOUTING = "CHECKOUTING"
    TRIALING = "TRIALING"
    ACTIVE = "ACTIVE"
    CANCELED = "CANCELED"
    INCOMPLETE = "INCOMPLETE"
    INCOMPLETE_EXPIRED = "INCOMPLETE_EXPIRED"
    PAST_DUE = "PAST_DUE"
    PAUSED = "PAUSED"
    UNPAID = "UNPAID"

    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    EXPIRES = "EXPIRES"
    PRICE_UPDATE_CHECKOUTING = "PRICE_UPDATE_CHECKOUTING"
