name: "[job] Run build library"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: make develop-ci

      - name: build
        run: make build-ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/