name: "[job] Check project in all branches"

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: make develop-ci

      - name: Run CI linters
        run: make lint-ci
