name: "[job] Notify Telegram"

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      environment:
        required: true
        type: string

    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      BACKEND_TELEGRAM_CHAT_ID:
        required: true

env:
  run_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          MESSAGE="
          🔔 [$GITHUB_REPOSITORY](https://github.com/$GITHUB_REPOSITORY)
          env: ${{ inputs.environment }}
          deploy: ${{ inputs.status }}
          by ${{ github.actor }}
          👉 [Github Workflow](${{ env.run_url }})"
          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed 's/\./\\./g; s/-/\\-/g; s/_/\\_/g; s/\*/\\*/g; s/!/\\!/g')
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.BACKEND_TELEGRAM_CHAT_ID }} \
            -d text="$ESCAPED_MESSAGE" \
            -d parse_mode="MarkdownV2"
