name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature**'
      - 'bugfix**'
      - 'fix**'
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MAJOR_PYTHON_VERSION: "3.12"

jobs:
  linting:
    name: Run linters and formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAJOR_PYTHON_VERSION }}

      - name: Install dependencies
        run: make develop-ci

      - name: Run lints on
        run: make lint-ci


  testing:
    needs: linting
    name: Testing (${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - name: Set up ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make develop-ci

      - name: Run tests
        run: make test-ci

  building:
    needs: testing
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAJOR_PYTHON_VERSION }}
      - name: Install dependencies
        run: make develop-ci
      - name: build
        run: make build-ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/

  publish-release:
    needs: building
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: ${{ github.ref_name }}
          body: Release new version of package **${{ github.event.repository.name }}** ${{ github.ref_name }}
          files: |
            dist/*
