name: Development pipeline

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  notify_start:
    name: Notify start
    uses: ./.github/workflows/_notify.yaml
    with:
      status: "🔄 STARTED"
      environment: "🛠 DEV"
    secrets: inherit

  check:
    name: Lint code and check format
    needs: notify_start
    uses: ./.github/workflows/_check.yaml

  test:
    name: Run tests
    needs: check
    uses: ./.github/workflows/_test.yaml

  build:
    if: github.event_name == 'workflow_dispatch'
    name: Build container image
    needs: test
    uses: ./.github/workflows/_build.yaml
    with:
      python-version: "3.12"
    secrets: inherit

  notify_finish:
    name: Notify success
    if: ${{ success() }}
    needs: build
    uses: ./.github/workflows/_notify.yaml
    with:
      status: "✅ SUCCEEDED"
      environment: "🛠 DEV"
    secrets: inherit

  notify_fail:
    name: Notify fail
    if: ${{ failure() }}
    needs: [check, test, build]
    uses: ./.github/workflows/_notify.yaml
    with:
      status: "❌ FAILED"
      environment: "🛠 DEV"
    secrets: inherit
